// Generated by gencpp from file adv_robotics/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ADV_ROBOTICS_MESSAGE_ADDTWOINTS_H
#define ADV_ROBOTICS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <adv_robotics/AddTwoIntsRequest.h>
#include <adv_robotics/AddTwoIntsResponse.h>


namespace adv_robotics
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace adv_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::adv_robotics::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::adv_robotics::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::adv_robotics::AddTwoInts > {
  static const char* value()
  {
    return "adv_robotics/AddTwoInts";
  }

  static const char* value(const ::adv_robotics::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::adv_robotics::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::adv_robotics::AddTwoInts > 
template<>
struct MD5Sum< ::adv_robotics::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::adv_robotics::AddTwoInts >::value();
  }
  static const char* value(const ::adv_robotics::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::adv_robotics::AddTwoIntsRequest> should match 
// service_traits::DataType< ::adv_robotics::AddTwoInts > 
template<>
struct DataType< ::adv_robotics::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::adv_robotics::AddTwoInts >::value();
  }
  static const char* value(const ::adv_robotics::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::adv_robotics::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::adv_robotics::AddTwoInts > 
template<>
struct MD5Sum< ::adv_robotics::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::adv_robotics::AddTwoInts >::value();
  }
  static const char* value(const ::adv_robotics::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::adv_robotics::AddTwoIntsResponse> should match 
// service_traits::DataType< ::adv_robotics::AddTwoInts > 
template<>
struct DataType< ::adv_robotics::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::adv_robotics::AddTwoInts >::value();
  }
  static const char* value(const ::adv_robotics::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADV_ROBOTICS_MESSAGE_ADDTWOINTS_H
